### ISSUE TITLE
Rune Strike Missing from WotLK Spell List

### ISSUE THREAD

**Issue by scrubnoobwow** [Ralgathor/LibClassicSwingTimerAPI#31]
The Death Knight ability [Rune Strike](https://www.wowhead.com/wotlk/spell=56815/rune-strike) needs to be added to `next_melee_spells` for `isWrath`

The spell ID is 56815, and adding the single line to LibClassicSwingTimerAPI.lua correctly allowed to swing timer to reset after casting Rune Strike on the live WotLK client

**Comment by Ralgathor** [comment]
Thx for the feedback. I need to update a bunch of other spell id I will do a new release when it will be done.

**Comment by Ralgathor** [comment]
Fixed in https://github.com/Ralgathor/LibClassicSwingTimerAPI/commit/ecc5e67224bfc5607fb1af0548a169067f2ee4eb and released in [v1.3.2](https://github.com/Ralgathor/LibClassicSwingTimerAPI/releases/tag/v1.3.2)
