### ISSUE TITLE
Lua error on next swing after using warrior's Slam ability

### ISSUE THREAD

**Issue by be-rational** [Ralgathor/LibClassicSwingTimerAPI#37]
When I'm playing my warrior and use the Slam ability, the next swing following Slam gives me a lua error.
Sorry I don't really know how much of the error I'm supposed to copy paste but here's the whole thing:

23x ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI-8.lua:476: attempt to call method 'SwingEnd' (a nil value)
[string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI-8.lua"]:476: in function <...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:475>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 PLAYER_ENTER_COMBAT = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:576
 ADDON_LOADED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:189
 callbacks = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:200
 UNIT_SPELLCAST_START = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:508
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:536
 PLAYER_EQUIPMENT_CHANGED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:565
 UNIT_SPELLCAST_INTERRUPTED_OR_FAILED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:407
 PLAYER_LEAVE_COMBAT = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:587
 PLAYER_TARGET_CHANGED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:240
 UnregisterAllCallbacks = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SwingTimerInfo = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:165
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:279
 target = <table> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:435
 RegisterCallback = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 player = <table> {
 }
 UNIT_ATTACK_SPEED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:354
 UnregisterCallback = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:546
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:442
 UnitSwingTimerInfo = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:175
 UNIT_SPELLCAST_FAILED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:438
 getUnit = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:155
}
(*temporary) = "mainhand"
(*temporary) = "attempt to call method 'SwingEnd' (a nil value)"
self = <table> {
 PLAYER_ENTER_COMBAT = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:576
 ADDON_LOADED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:189
 callbacks = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:200
 UNIT_SPELLCAST_START = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:508
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:536
 PLAYER_EQUIPMENT_CHANGED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:565
 UNIT_SPELLCAST_INTERRUPTED_OR_FAILED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:407
 PLAYER_LEAVE_COMBAT = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:587
 PLAYER_TARGET_CHANGED = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:240
 UnregisterAllCallbacks = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SwingTimerInfo = <function> defined @LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:165
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @

**Comment by Ralgathor** [comment]
What release version of the lib are you using?

**Comment by be-rational** [comment]
I was using LibClassicSwingTimerAPI-v1.4.0-alpha-1
switched to LibClassicSwingTimerAPI-v1.3.2 and seems fine now, not sure how I ended up with the alpha version

**Comment by Ralgathor** [comment]
Yes Alpha is under devlopment to support Target swingtimer so not stable.

**Comment by Neran28** [comment]
Hello,
i do get two errors with v1.3.2 and the newly realeased v1.4.0 when using Slam as a warrior. Also the timer returns a negative number while casting Slam.

ID: 1
Error occured in: Global
Count: 1
Message: ..\SharedXML\C_TimerAugment.lua line 30:
   C_Timer.After requires a non-negative duration
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: After()
   [string "@..\SharedXML\C_TimerAugment.lua"]:30:
      ..\SharedXML\C_TimerAugment.lua:11
   [string "=(tail call)"]: ?
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:313: UNIT_SPELLCAST_INTERRUPTED_OR_FAILED()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:329: ?()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487:
      ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483
   [string "=[C]"]: MoveBackwardStart()
   [string "MOVEBACKWARD"]:2:
      [string "MOVEBACKWARD"]:1
Locals:

and this error:

Error occured in: Global
Count: 1
Message: ..\SharedXML\C_TimerAugment.lua line 30:
   C_Timer.After requires a non-negative duration
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: After()
   [string "@..\SharedXML\C_TimerAugment.lua"]:30:
      ..\SharedXML\C_TimerAugment.lua:11
   [string "=(tail call)"]: ?
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:364: ?()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487:
      ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483
Locals:

**Comment by Ralgathor** [comment]
> Hello, i do get two errors with v1.3.2 and the newly realeased v1.4.0 when using Slam as a warrior. Also the timer returns a negative number while casting Slam.
> 
> ID: 1 Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:313: UNIT_SPELLCAST_INTERRUPTED_OR_FAILED() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:329: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 [string "=[C]"]: MoveBackwardStart() [string "MOVEBACKWARD"]:2: [string "MOVEBACKWARD"]:1 Locals:
> 
> and this error:
> 
> Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:364: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 Locals:

This error seem to happen when the Slam cast is interrupted. Can you give more information on the context?

**Comment by Neran28** [comment]
> > Hello, i do get two errors with v1.3.2 and the newly realeased v1.4.0 when using Slam as a warrior. Also the timer returns a negative number while casting Slam.
> > ID: 1 Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:313: UNIT_SPELLCAST_INTERRUPTED_OR_FAILED() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:329: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 [string "=[C]"]: MoveBackwardStart() [string "MOVEBACKWARD"]:2: [string "MOVEBACKWARD"]:1 Locals:
> > and this error:
> > Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:364: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 Locals:
> 
> This error seem to happen when the Slam cast is interrupted. Can you give more information on the context?

I am just using Slam on a hostile target. Probably I was also interrupting the cast on some occasions, however it also occurs when the ability starts casting.

**Comment by Ralgathor** [comment]
> > > Hello, i do get two errors with v1.3.2 and the newly realeased v1.4.0 when using Slam as a warrior. Also the timer returns a negative number while casting Slam.
> > > ID: 1 Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:313: UNIT_SPELLCAST_INTERRUPTED_OR_FAILED() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:329: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 [string "=[C]"]: MoveBackwardStart() [string "MOVEBACKWARD"]:2: [string "MOVEBACKWARD"]:1 Locals:
> > > and this error:
> > > Error occured in: Global Count: 1 Message: ..\SharedXML\C_TimerAugment.lua line 30: C_Timer.After requires a non-negative duration Debug: [string "=[C]"]: ? [string "=[C]"]: After() [string "@..\SharedXML\C_TimerAugment.lua"]:30: ..\SharedXML\C_TimerAugment.lua:11 [string "=(tail call)"]: ? [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:364: ?() [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487: ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483 Locals:
> > 
> > 
> > This error seem to happen when the Slam cast is interrupted. Can you give more information on the context?
> 
> I am just using Slam on a hostile target. Probably I was also interrupting the cast on some occasions, however it also occurs when the ability starts casting.

Did you use any /stopattack macro with your Slam ability ? The only way for me to reproduce this issue is by casting Slam without attacking the target or stopattacking the target during the Slam cast.

**Comment by Neran28** [comment]
> > > This error seem to happen when the Slam cast is interrupted. Can you give more information on the context?
> > 
> > 
> > I am just using Slam on a hostile target. Probably I was also interrupting the cast on some occasions, however it also occurs when the ability starts casting.
> 
> Did you use any /stopattack macro with your Slam ability ? The only way for me to reproduce this issue is by casting Slam without attacking the target or stopattacking the target during the Slam cast.

I am not using a macro with slam. However I did attack without having a target selected before using the ability. So the target was selected by using slam. 

I checked this again. I now selected a target from the start. Then i am using slam as my first attack. There was no autoattack before.
**Result:**
Message: ..\SharedXML\C_TimerAugment.lua line 30:
   C_Timer.After requires a non-negative duration
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: After()
   [string "@..\SharedXML\C_TimerAugment.lua"]:30:
      ..\SharedXML\C_TimerAugment.lua:11
   [string "=(tail call)"]: ?
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:364: ?()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487:
      ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483
Locals:

Next thing i did was /reload

Then again i started using slam as my first attack and interrupted it with ESC. 
**Result:**

Message: ..\SharedXML\C_TimerAugment.lua line 30:
   C_Timer.After requires a non-negative duration
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: After()
   [string "@..\SharedXML\C_TimerAugment.lua"]:30:
      ..\SharedXML\C_TimerAugment.lua:11
   [string "=(tail call)"]: ?
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:313: UNIT_SPELLCAST_INTERRUPTED_OR_FAILED()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:329: ?()
   [string "@LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua"]:487:
      ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:483
Locals:

If I do exactly the same without having a target selected from the start then its exactly the same result.
If I do this while autoattacking (so not using slam as my first action before autoattacking) then there is no error.

**Comment by Ralgathor** [comment]
FIxed on the following release https://github.com/Ralgathor/LibClassicSwingTimerAPI/releases/tag/v1.4.1
