### ISSUE TITLE
v2.0.0 Lua error

### ISSUE THREAD

**Issue by be-rational** [Ralgathor/LibClassicSwingTimerAPI#43]
Not sure what causes it.

3x ...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI-15.lua:467: attempt to call method 'SwingEnd' (a nil value)
[string "@Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI-15.lua"]:467: in function <...\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:466>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 PLAYER_ENTER_COMBAT = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:620
 ADDON_LOADED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:212
 callbacks = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:223
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:552
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:580
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:609
 UNIT_SPELLCAST_INTERRUPTED_OR_FAILED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:441
 PLAYER_LEAVE_COMBAT = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:631
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:265
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:164
 SwingTimerInfo = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:188
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:310
 target = <table> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:473
 RegisterCallback = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 player = <table> {
 }
 UNIT_ATTACK_SPEED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:385
 UnregisterCallback = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:590
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:480
 UnitSwingTimerInfo = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:198
 UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:476
 getUnit = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:178
}
(*temporary) = "offhand"
(*temporary) = "attempt to call method 'SwingEnd' (a nil value)"
self = <table> {
 PLAYER_ENTER_COMBAT = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:620
 ADDON_LOADED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:212
 callbacks = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:223
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:552
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:580
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:609
 UNIT_SPELLCAST_INTERRUPTED_OR_FAILED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:441
 PLAYER_LEAVE_COMBAT = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:631
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:265
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:164
 SwingTimerInfo = <function> defined @Interface\AddOns\LibClassicSwingTimerAPI\LibClassicSwingTimerAPI.lua:188
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @I

**Comment by Ralgathor** [comment]
Fixed in release 2.0.1 https://github.com/Ralgathor/LibClassicSwingTimerAPI/releases/tag/v2.0.1.

Thanks for the report !
